#pragma once

enum class Operator
{
	ADD, MINUS, MULTIPLY, DIVIDE, MOD,
	EQUALS, NOT_EQUALS, LESS, GREATER, LESS_EQUALS, GREATER_EQUALS,
	LOGICAL_AND, LOGICAL_OR,
	BITWISE_OR, BITWISE_AND, BITSHIFT_LEFT, BITSHIFT_RIGHT
};