#pragma once

#include "Common.h"

enum class TokenTypeT
{
	END, UNKNOWN, IDENTIFIER, IMPORT, THROW, CATCH, CLASS, ENUM,
	UINT8, UINT16, UINT32, UINT64, INT8, INT16, INT32, INT64, REAL32, REAL64, BOOL, CHAR, STRING,
	VOID_T, NULLPTR, THIS, ASTERISK, DOT, SEMICOLON, TILDE, NATIVE_OFFSET, NATIVE, NATIVE_SIZE,
	OPEN_BRACE, CLOSE_BRACE, OPEN_BRACKET, CLOSE_BRACKET, OPEN_PAREN, CLOSE_PAREN,
	NUMBER_LITERAL, STRING_LITERAL, CHAR_LITERAL,
	PLUS, MINUS, SLASH, MOD, COLON, COMMA,
	EQUALS, EQUALS_EQUALS, LESS, GREATER, LESS_EQUALS, GREATER_EQUALS, NOT_EQUAL, NOT, PIPE, AND,
	LOGICAL_AND, LOGICAL_OR, SIZE_OF, NEW, DELETE_T,
	PLUS_PLUS, MINUS_MINUS, PLUS_EQUALS, MINUS_EQUALS, TIMES_EQUALS, DIVIDE_EQUALS, MOD_EQUALS,
	PUBLIC, PRIVATE, STATIC, OPERATOR, RETURN,
	IF, ELSE, FOR, WHILE, TRUE_T, FALSE_T,
	TEMPLATE, ARROW,
	BITSHIFT_LEFT, BITSHIFT_RIGHT,
	STRLEN, BREAK, CONTINUE, INHERIT, VIRTUAL, STR_TO_INT, INT_TO_STR, OFFSETOF, BREAKPOINT,
};

struct Token
{
	TokenTypeT type;
	char* text;
	uint32 length;

	uint32 line;
	uint32 column;
};

struct Tokenizer
{
	char* at;

	uint32 currentLine = 1;
	uint32 currentColumn = 1;

	Token GetToken();
	bool Expect(TokenTypeT type, Token* token = nullptr);
	Token PeekToken();
	void SetPeek(const Token& peek);

	static bool IsTokenPrimitiveType(const Token& token);
private:
	void EatWhitespace();
};